HyGoApp/urls.py
# from django.conf.urls import include, url,handler404

# handler404='views.page_not_found'

# urlpatterns = [
        
# ]			

from django.conf.urls import handler404

handler404='views.page_not_found'		

handler500='views.server_error'	

SiteProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings #Added
from django.conf.urls.static import static #Added 
from rest_framework import routers
from HyGoApp.api.viewsets import VideoViewSet, TechnicalVideoViewSet, ProductViewSet, FishImageViewSet

# Rest API related url conf (START)
router = routers.DefaultRouter()
router.register("videos", VideoViewSet)
router.register("technical-videos", TechnicalVideoViewSet)
router.register("products", ProductViewSet)
router.register("fish-images", FishImageViewSet)

# END 
urlpatterns = [
    # Rest API
    url(r"^hygull/api/", include(router.urls) ),

    url(r"^blogs/r-programming/$","HyGoApp.views.rscript",name="rscript"),
    url(r"^blogs/supermarket/$","HyGoApp.views.supermarket",name="supermarket"),
    url(r"^image-scrapper/$", "HyGoApp.views.scrapped_image_links",name="scrapped_image_links"),
    # Examples:
    # url(r'^$', 'HyGoApp.views.login_with_google', name='home'),
    url(r'^$', 'HyGoApp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^login/$', 'HyGoApp.views.login', name='login'),
    url(r'^login2/$', 'HyGoApp.views.login2', name='login2'),
    url(r'^submit/$', 'HyGoApp.views.success', name='success'),
    url(r'^error/$', 'HyGoApp.views.error', name='error'),
    url(r"^url/error_msg/","HyGoApp.views.url_error_message",name='url_error_message'),
    url(r'^admin/', include(admin.site.urls)),
    url(r"^hygull/technical-things/$", "HyGoApp.views.more", name="more"),
    url(r"^blogs/$","HyGoApp.views.blogs",name="blogs"),
    url(r"^aboutus/$","HyGoApp.views.aboutus",name="aboutus"),
    url(r"^posts/$","HyGoApp.views.posts",name="posts"),
    url(r"^posts/create/$","HyGoApp.views.posts_create",name="posts_create"),
    url(r"^created/$","HyGoApp.views.posts_created",name="servirall_aboutus"),
    url(r"^posts/videos/$","HyGoApp.views.posted_videos",name='posted_videos'),
    url(r"^posts/videos/create/$","HyGoApp.views.posts_videos_create",name='posts_videos_create'),

    url(r"^dtl_home/$","HyGoApp.views.dtl_home",name="dtl_home"),
    url(r"^dtl_home/aboutus/$","HyGoApp.views.dtl_aboutus",name="servirall_aboutus"),
    #url(r"^dtl_base/contact/$","HyGoApp.views.dtl_contact",name="servirall_contact"),

    url(r'^profile_info/(.*)$', "HyGoApp.views.profile_info",name='profile_info'),
    url(r'^accounts/', include('registration.backends.default.urls')), #dajngo-registration-redux
]	#+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)		

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)	

HyGoApp/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError

# Create your models here.
class SignUp(models.Model):
	username = models.CharField(max_length=20,null=True,blank=True)
	email = models.EmailField(max_length=30)
	created_at = models.DateTimeField(auto_now_add=True,auto_now=False)
	updated_at = models.DateTimeField(auto_now_add=False,auto_now=True)

	def __unicode__(self):  
		return self.username


class Post(models.Model):
	title = models.CharField(max_length=150,null=False,blank=False)
	description = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True,auto_now=False)
	updated_at = models.DateTimeField(auto_now_add=False,auto_now=True)

	def __unicode__(self):
		return self.title

	def get_absolute_path(self):
		return "http://rishikesh67.pythonaywhere.com/posts/%d"%(self.id)



class Video(models.Model):
	title = models.CharField(max_length=150,null=False,blank=False)
	url = models.TextField()

	def __unicode__(self):
		return self.title

class VideoVirtualReality(models.Model):
	title = models.CharField(max_length=150,null=False,blank=False)
	url = models.CharField(max_length=150,null=False,blank=False)

	def __unicode__(self):
		return self.title

class Markdown(models.Model):
	name = models.CharField(max_length=100, blank=False)
	markdown_text = models.TextField()

	def __unicode__(self):
		return self.name

class Product(models.Model):
	""" Product model """
	title = models.CharField(max_length=500, blank=False)
	image = models.TextField(blank=False)
	price = models.FloatField(blank=False)
	stock_status = models.IntegerField(validators=[MaxValueValidator(1), MinValueValidator(0)], blank=False)
	target_url = models.TextField(blank=False)
	merchant = models.CharField(max_length=5,blank=False)

	def __unicode__(self):
		return self.title

class Click(models.Model):
	clicks = models.BigIntegerField()


def validate_discount(value):
	if value < 0.0:
		raise ValidationError("discount should be positive")

def validate_description(text):
	if len(text) < 20 or len(text) > 300:
		raise ValidationError("Description should have 25-300 characters, You provided %d"%(len(text)))

desc = "Fish are vertebrates which live in water and respire (get oxygen) with gills. They lack limbs with digits (fingers & toes).\nThis is a definition which does not quite work: some amphibia also live in water and have external gills, but they are not fishes."

class FishImage(models.Model):
	""" A class that defines the structure of User object """
	COLOR_CHOICES = (
	    (1, 'Type1'),
	    (2, 'Type2'),
	    (3, 'Type3'),
	    (4, 'Type4'),
	    (5, 'Type5'),
	    (6, 'Type6'),
	    (7, "Other"),
	)

	flesh_name = models.CharField(max_length=50, blank=False)	#Required
	flesh_type = models.CharField(max_length=50, blank=False)
	flesh_pic = models.ImageField(default="https://en.wikipedia.org/wiki/List_of_types_of_seafood#/media/File:Squilla_mantis_(l%27Ametlla)_brighter_and_quality.jpg", max_length=200)
	flesh_type = models.IntegerField(choices=COLOR_CHOICES, default='Type0', blank=True)
	price = models.FloatField(blank=False)
	discount = models.IntegerField(validators=[validate_discount], default=0, blank=True)
	description = models.TextField(default=desc, validators=[validate_description], blank=False, null=False)

	def __unicode__(self):
		return self.flesh_name

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
       {% block js_angular_link %}
       {% endblock %}
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}MVP Landing{% endblock %}</title>

    {% include 'head_css.html' %}

      <style>
      {% block style %}{% endblock %}
      </style>
  </head>

  <body>
  {% include 'navbar.html' %}

            {% block jumbotron %}
          
            {% endblock %}
<div class="container">
            

          
    {% block content %}

    {% endblock %}
              

    </div> <!-- /container -->

    {% include "javascript.html" %}

    {% block js_github_block %}
    {% endblock %}
    
  </body>
</html>

templates/blogs.html
{% extends "common.html" %}

{% block row1_column2 %}
<div class="col-md-7 col-md-7 col-xs-12 text-center"><!--column2 start-->
    <div class="row"><!--Panel row 1 starts-->
      <div class="col-sm-12 col-xs-12">
          <div class="panel panel-success">
            <div class="panel-heading">
                  <h1><a href="/blogs/supermarket/">Supermarket</a><h1>
            </div>
            <div class="panel-body">
              <a href="/blogs/supermarket/"><img  src="http://www.bluedogconsulting.co.uk/wp-content/uploads/2013/03/BusinessTechnicalSupport.jpg" class="img-responsive">
            </div></a>
            <div class="panel-footer">
              <h5 style="font-family: tahoma;font-weight: bold;">A <span style="color:blue">supermarket</span>   is a self-service shop offering a wide variety of food and household products, organized into aisles.
            </div>
          </div>
      </div>

      <div class="col-sm-12 text-center">
            <hr>
            <h1><a href="https://github.com/hygull/type-script/">TypeScript - Github</a></h1>
            <hr>
            <h1><a href="https://github.com/hygull/rscript">R programming - Github</a></h1>
            <hr>
            <h1><a href="/hygull/technical-things">More than more</a></h1>
      
      </div>
    </div>  
</div>
{% endblock %}

<!-- {% block next_link %}
 <ul class="pager text-center">
    <li><a href="#">Next</a></li>
  </ul>
{% endblock %} -->
http://www.pyimagesearch.com/2014/01/12/my-top-9-favorite-python-libraries-for-building-image-search-engines/

templates/dtl_aboutus.html
{% extends "./dtl_base.html" %}


{% block content %}
		<div class="row">
			<div class='col-lg-4 col-xs-12'>
				<div class='panel panel-success' >
					<div class="panel-heading">
						<h4 style="text-align: center"><i class="fa fa-eye" aria-hidden="true"></i> &nbsp;Help others<h5>
					</div>
					<div class="panel-body">
						<div class="col-xs-12 col-lg-12">
						<img class="img-rounded" src="https://image.freepik.com/free-icon/man-helping-other-to-stand-up-from-the-floor_318-29254.jpg" width="70%" height="70%" role="button" alt="help">
						<hr>
						</div>

						<div class="col-xs-12 col-lg-12">
						<p style='font-family: tahoma;text-align:center'>Helping unables will definitely benefit you in future at any point of time. <br>Effort never get lost.</p><hr>
							<span class="likebtn-wrapper" data-theme="youtube" data-rich_snippet="true" data-identifier="item_1"></span>
						</div>
					</div>
				</div>
			</div>
			<div class='col-lg-4 col-xs-12'>
				<div class='panel panel-warning' >
					<div class="panel-heading">
						<h4 style="text-align: center"><i class="fa fa-sign-language" aria-hidden="true"></i> &nbsp;Serve poors<h4>
					</div>
					<div class="panel-body">
						<div class="col-xs-12 col-lg-12">
						<img src="http://www.livemint.com/rf/Image-621x414/LiveMint/Period1/2015/08/27/Photos/MOTHER%201-kmQB--621x414@LiveMint.jpg" width="100%" height="130%" role="button" alt="help">
						<hr>
						</div>

						<div class="col-xs-12 col-lg-12">
						<p style='font-family: tahoma;text-align: center'>Serving only family members is not an identification of a good people. We should try to serve all as we all are from the same universe.</p><hr>
							
						</div>
						
					</div>
				</div>
			</div>
			<div class='col-lg-4 col-xs-12'>
				<div class='panel panel-info' >
					<div class="panel-heading">
						<h4 style="text-align: center"><i class="fa fa-wheelchair-alt" aria-hidden="true"></i> &nbsp;Love all<h5>
					</div>
					<div class="panel-body">
						<div class="col-xs-12 col-lg-12">
						<img src="http://www.lifenews.com/wp-content/uploads/2016/09/motherteresa15.jpg" width="100%" height="130%" role="button" alt="help">
						<hr>
						</div>

						<div class="col-xs-12 col-lg-12">
						<p style='font-family: tahoma;text-align: center'>We should love all in the world. Most of us hate animals, poors and others.<br> It is not good.</p><hr>
							
						</div>
					
						
					</div>
				</div>
			</div>
		</div>
		<div class="row">
		<div class="col-xs-12 col-lg-12">
			<div class="panel panel-success">
				<div class='panel-heading'>
					<h4 style="text-align: center"><i class="fa fa-ambulance" aria-hidden="true"></i> &nbsp;We have to love them a lot<h5>
				</div>
				<div class="panel-body">
					<div class="col-lg-6 col-xs-12">
					<img src="http://previews.123rf.com/images/anry01/anry011207/anry01120700073/14999987-Rural-children-are-playing-on-the-road--Stock-Photo-poverty-child-children.jpg" width="100%" height="80%" role="button" alt="help">
					</div>
					<div class="col-lg-6 col-xs-12">
					<img src="http://venturesafrica.com/wp-content/uploads/2015/09/mother-theresa.jpg" width="100%" height="100%" role="button" alt="help">
					</div>
				
				</div>
				<div class='panel-footer'>
					<center>Mother Teresa was the great lover of children, poors and all. Visit <a href='https://en.wikipedia.org/wiki/Mother_Teresa'>here </a> to know more about Mother Teresa</center>
				</div>
			</div>
			<div class="panel panel-info">
				<div class='panel-heading'>
					<h4 style="text-align: center"><i class="fa fa-users" aria-hidden="true"></i> &nbsp;Doctors & their team both are Great<h5>
				</div>
				<div class="panel-body">
					<div class="col-lg-6 col-xs-12">
					<img src="http://indiaatyourservice.com/images/portfolio/h7.png" width="100%" height="80%" role="button" alt="help">
					</div>
					<div class="col-lg-6 col-xs-12">
					<img src="http://cdn.inquisitr.com/wp-content/uploads/2015/10/heart-surgery.jpg" width="100%" height="100%" role="button" alt="hospital">
					</div>
				
				</div>
				<div class='panel-footer'>
					<center>Hospital becomes like a temple and heaven for a patient &amp; for their relatives</center>
				</div>
			</div>
			<div class="panel panel-info">
				<div class='panel-heading'>
					<h4 style="text-align: center"> <i class="fa fa-hand-peace-o" aria-hidden="true"></i> &nbsp;Love yourself<h5>
				</div>
				<div class="panel-body">
					<div class="col-lg-10 col-xs-12">
						<img src="http://b2view.biosector2.com/wp-content/uploads/2015/08/ThinkstockPhotos-155283331.jpg" width="100%" height="100%" role="button" alt="hospital">
					</div>
					<div class="col-lg-2 col-xs-12">
						<div class="panel panel-primary">
							<div class='panel-heading'>
								<h5 style="text-align: center"><i class="fa fa-user-o" aria-hidden="true"></i> &nbsp;My body<h5>
							</div>
							<div class="panel-body">
								<center>This body is like temple & we should respect & love ourself.Just as you need to respect your body, you also need to respect your mind. Challenge yourself with new experiences and information. <hr>The people who don't respect their body they don't want to live in the world & they don't have specific target in their life.So love yourself.</center>
							
							</div>
							<div class="panel-footer">
							<center>Visit <a href="https://www.lds.org/youth/learn/yw/plan-of-salvation/sacred?lang=eng" target='_blank'>here</a> to read about body</center>
							</div>
						</div>
					</div>
				</div>
				<div class='panel-footer'>
					<center>We should respect ourself.</center>
				</div>
			</div>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h4 style="text-align: center;"><i class="fa fa-heart" aria-hidden="true"></i> &nbsp;Heart touching & inspirational videos</h4>
				</div>
				<div class="panel-body">
					<div class="col-lg-6 col-xs-12">
						<iframe width="98%" height="315" src="https://www.youtube.com/embed/EvHmSze1ric" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="col-lg-6 col-xs-12">
						<iframe width="98%" height="315" src="https://www.youtube.com/embed/QmbWAFzOeyg" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="col-lg-6 col-xs-12">
						<iframe width="98%" height="315" src="https://www.youtube.com/embed/95MXXRi3rfM" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="col-lg-6 col-xs-12">
						<iframe width="98%" height="315" src="https://www.youtube.com/embed/XHEcu97FYZ4" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="col-lg-6 col-xs-12">
						<iframe width="98%" height="315" src="https://www.youtube.com/embed/xjUz95vtlew" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="col-lg-6 col-xs-12">
						<iframe width="98%" height="315" src="https://www.youtube.com/embed/5ubiEFxt_TQ" frameborder="0" allowfullscreen></iframe>
					</div>

					<div class="col-lg-6 col-xs-12">
						<iframe width="98%" height="315" src="https://www.youtube.com/embed/AIn2zCSmlh0" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="col-lg-6 col-xs-12">
						<iframe width="98%" height="315" src="https://www.youtube.com/embed/i_kZUVc8nDo" frameborder="0" allowfullscreen></iframe>
					</div>
					<!--Add videos end-->
					<br/>					
					<center><a role="button" href='https://www.youtube.com/watch?v=XHEcu97FYZ4' target="_blank" class="btn btn-md btn-success">More videos &raquo;</a></center>
				</div>

				<div class="panel-footer">
					<center>Mother teresa was a great woman.</center>
				</div>
			</div>
		</div>
		</div>
{% endblock %}
<div>
	

templates/dtl_navbar.html
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><i class="fa fa-ravelry" aria-hidden="true"></i> &nbsp;Servirall</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="/dtl_home/aboutus/">About</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="/">Golang</a></li>
            <li><a href="/posts/videos/">Videos</a></li>
            <li><a href="/blogs/supermarket/">PIL</a></li>
            <li><a href="/image-scrapper/">PicScrapper</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="#" target="_blank">Admission</a></li>
            <li><a href="https://www.practo.com/" target="_blank">Doctor Booking</a></li>
            <li><a href="https://ifsc.bankifsccode.com/" target="_blank">Bank details</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Error</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="icon" type="image/gif/png" href="https://cdn2.iconfinder.com/data/icons/goodreads-1/512/goodreads-round-4-256.png">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
 <!--  <h2>Alerts</h2>
  <div class="alert alert-success">
    <strong>Success!</strong> This alert box could indicate a successful or positive action.
  </div>
  <div class="alert alert-info">
    <strong>Info!</strong> This alert box could indicate a neutral informative change or action.
  </div>
  <div class="alert alert-warning">
    <strong>Warning!</strong> This alert box could indicate a warning that might need attention.
  </div> -->
  <center>
  <div class="alert alert-danger">
    <h1 >You didn't enter <strong>Proper data</strong><h1><hr>
  </div>
  <div class="alert alert-info">
   <h2 > <strong>Username </strong>should contains only alphabet with with first letter capitalize,max length is 20</h2>
   <h2 > <strong>Email </strong>should be only gmail, max length is 30. eg. rishikesh@gmail.com</h2>
  </div>
  <center>
</div>

</body>
</html>

templates/posts.html
{% extends "common.html" %}


{% block row1_column2 %}
	 <div class="col-md-7 col-xs-12 col-sm-7"><!--column2 start-->
	<!--  <center> <a class="btn btn-lg btn-info" href="/posts/create/" role="button"><h4><i class="fa fa-pencil fa-1x" aria-hidden="true"></i>&nbsp;Write a new post</h4></a></center><br> -->
	 {% for post in posts %}
		<div class='panel panel-success'>
	 		<div class='panel-heading'>
				<h4 style='font-weight: bold;'>{{ post.title }}</h4>
			</div>
			<div class='panel-body' style='margin:0'>
				<h5 style='font-family: sans-serif;margin:0'><pre styple='margin:0'>{{ post.description }}</pre></h5>
			</div>
			<div class='panel-body'>
			 <div class="fb-like" data-href="{{ post.get_absolute_path }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

			 <div class="fb-follow" data-href="{{ post.get_absolute_path }}" data-layout="standard" data-size="small" data-show-faces="true"></div>
			</div>
		</div><!--panel ends-->
	{% endfor %}

	{# It will appear if the user is not logged in #}
	{{ posts_message|safe }}
	</div><!--column2 end-->
{% endblock %}

templates/posts_videos_create.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Post a new video by just pasting the URL inside area textarea </title>
  <link rel="icon" type="image/gif/png" href="https://cdn2.iconfinder.com/data/icons/goodreads-1/512/goodreads-round-4-256.png">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style type="text/css">
    body{
      background-color: black;
    }
    form label{
      color:lightgreen;
    }
    strong {
      color:white;
    }
    .form-group-has-error {
      color:white;
    }
    .hidden_img{
      display: none;
      visibility:hidden;
    }
    @media only screen and (max-width: 540px){
      .hidden_img{
        display: block;
        visibility: visible;
      }
    }

    img:hover{
      width: 41%;
    }

    #id_title,#id_url{
      background-color: gray;
      font-size: 16px;
      color:white;
    }

    ::-webkit-input-placeholder { /* Chrome */
        color: green;
    }
  </style>
</head>
<body>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8&appId=183960815416449";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="container">
  <h3 class="text-center" style="color:lightgreen;"><i class="fa fa-caret-square-o-right" aria-hidden="true"></i> &nbsp; Post a video by pasting its URL</h3>

  <center><span style="color: lightgreen">Click<span> &raquo; <a href="/" style='color:pink'><i class="fa fa-motorcycle" aria-hidden="true"></i> &nbsp;Golang</a>&nbsp; | &nbsp;
  <a href="/dtl_home/" style='color:pink'><i class="fa fa-plane" aria-hidden="true"></i> &nbsp;Servirall</a>&nbsp; | &nbsp;   <a href="/posts/videos/" style='color:pink'><i class="fa fa-certificate" aria-hidden="true"></i> &nbsp;All videos</a><br>
  <div class="fb-like" data-href="http://rishikesh67.pythonanywhere.com/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></center>
  <hr>
      <div class="row">
      <div class="col-lg-3 col-sm-3 col-md-3 col-xs-3 text-center">
         <center> 
          <a href='/'>  
              <img title='Home page' src="https://cdn3.iconfinder.com/data/icons/luchesa-vol-9/128/Home-512.png" class='img-responsive' width="40%" height="40%"  alt="home">
          </a><br><br>
            
            <a href="/posts/">
            <img title='All posts' src="https://cdn2.iconfinder.com/data/icons/device-color/512/Untitled-19-512.png" class='img-responsive' width="40%" height="40%" role="button" alt="note"><br>
            </a>

            <img src="https://cdn1.iconfinder.com/data/icons/business-13/6144/13-512.png" class='img-responsive' width="40%" height="40%" alt="clock"><br>

            <img src="https://cdn1.iconfinder.com/data/icons/babies-color/300/19-512.png" class='img-responsive' width="40%" height="40%"  alt="mother"><br>

            <img class='hidden_img' src="https://cdn4.iconfinder.com/data/icons/democracy/500/Political_14-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"><br>

          <img class='hidden_img' src="https://cdn1.iconfinder.com/data/icons/people-faces/76/avatar_person_human_user_man_woman-12-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"><br>

          <img class='hidden_img' src="https://cdn0.iconfinder.com/data/icons/business-6-2/48/269-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"><br>

          <img class='hidden_img' src="https://cdn1.iconfinder.com/data/icons/people-faces/76/avatar_person_human_user_man_woman-12-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"><br>

            </center>
      </div>
      <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 text-center">
        <form class="form" method="POST" action="">{% csrf_token %}<!--In case of action included-->
            {{ form|crispy }}  <!--{{ form.as_p }}-->

            <button type="submit" class="btn btn-primary btn-block"><h5> <i class="fa fa-paper-plane" aria-hidden="true"></i>&nbsp;Publish</h5></button>

        </form>

      </div> 

            <div class="col-lg-3 col-sm-3 col-md-3 col-xs-3 text-center">
              <center><img src="https://cdn0.iconfinder.com/data/icons/seo-and-internet-marketing-1-1/512/22-512.png" class='img-responsive' width="40%" height="40%" alt="innovation"><br>
            
            <img src="https://cdn0.iconfinder.com/data/icons/purple-set/512/pen_markerpen_writer_ink-512.png" class='img-responsive' width="40%" height="40%"  alt="pen"><br>

            <img src="https://cdn3.iconfinder.com/data/icons/humano2/128x128/apps/openofficeorg-writer.png" class='img-responsive' width="40%" height="40%"  alt="pot"><br>
            <img src="https://cdn1.iconfinder.com/data/icons/elevator/154/elevator-ventilation-climate-conditioner-air-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"><br>

          <img class='hidden_img' src="https://cdn1.iconfinder.com/data/icons/creative-process-14/512/Video_Editing-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"><br>

          <img class='hidden_img' src="https://cdn1.iconfinder.com/data/icons/creative-process-14/512/Idea-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"><br>

          <img class='hidden_img' src="https://cdn1.iconfinder.com/data/icons/creative-process-14/512/Apps_Builder-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"><br>
          <img class='hidden_img' src="https://cdn1.iconfinder.com/data/icons/creative-process-14/512/3D_Modeling-512.png" class='img-responsive' width="40%" height="40%" alt="desktop"></center><br>
      </div> 
      </div>
    </div>
</body>
</html>